admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_time_in:
    path:     /admin/time_in/{id}/{passw}
    defaults: { _controller: AdminBundle:Default:timeIn }

admin_time_in_no_params:
    path:     /admin/time_in/
    defaults: { _controller: AdminBundle:Default:timeIn }

request_email:
    path:     /send/request/email/{value}
    defaults: { _controller: AdminBundle:Default:sendRequest }

request_email_no_params:
    path:     /send/request/email/
    defaults: { _controller: AdminBundle:Default:sendRequest }

request_meeting:
    path:     /request/meeting/
    defaults: { _controller: AdminBundle:Default:requestMeeting }

request_leave:
    path:     /request/leave
    defaults: { _controller: AdminBundle:Default:requestLeave }

status_accept_with_params:
    path:    /status/accept/{id}/{id2}
    defaults: { _controller: AdminBundle:Default:statusAccept }
    
status_accept:
    path:    /status/accept/
    defaults: { _controller: AdminBundle:Default:statusAccept }

status_declined:
    path:    /declined
    defaults: { _controller: AdminBundle:Default:declinedRequest }

check_time:
    path: /checktime
    defaults: { _controller: AdminBundle:Default:checkTime }

admin_employee_report:
    path: /employee/report
    defaults: { _controller: AdminBundle:EmployeeReport:generateReport }

time_in:
    path: /timein
    defaults: { _controller: AdminBundle:Employee:TimeIn }

time_out:
    path: /timeout/
    defaults: { _controller: AdminBundle:Employee:TimeOut }

time_out_w_params:
    path: /timeout/{passw}
    defaults: { _controller: AdminBundle:Employee:TimeOut }

time_logs_page:
    path: /timelogs
    defaults: { _controller: AdminBundle:Default:timeLogs}

auto_time_out:
    path: /autotimeout
    defaults: { _controller: AdminBundle:Employee:AutoTimeOut }

admin_manage_working_time_new_day:
    path: /admin/timein/{type}
    defaults: { _controller: AdminBundle:Employee:ManageTimeOnNewDay }

admin_employee_list_report:
    path: /emplist/report
    defaults: { _controller:AdminBundle:EmployeeReport:generateEmployeeReport }