admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }

admin_dashboard_get_events:
    path:     /dashboard/events/get
    defaults: { _controller: AdminBundle:Dashboard:getCalendarEvents }

admin_time_in:
    path:     /admin/time_in/{id}/{passw}
    defaults: { _controller: AdminBundle:Admin:timeIn }

admin_time_in_no_params:
    path:     /admin/time_in/
    defaults: { _controller: AdminBundle:Admin:timeIn}

request_access_accepted:
    path: /requestaccepted
    defaults: { _controller: AdminBundle:Admin:acceptRequest }

admin_edit_employee_profile:
    path:     /admin/edit/empprofile
    defaults: { _controller: AdminBundle:Admin:adminEditProfile }

status_declined:
    path:    /declined
    defaults: { _controller: AdminBundle:Admin:declinedRequest }

request_access:
    path: /requestaccess
    defaults: {_controller: AdminBundle:Admin:requestAccess }



request_meeting:
    path:     /request/meeting/
    defaults: { _controller: AdminBundle:EmployeeRequest:requestMeeting }

request_leave:
    path:     /request/leave
    defaults: { _controller: AdminBundle:EmployeeRequest:requestLeave }

change_status:
    path:    /status/change/
    defaults: { _controller: AdminBundle:EmployeeRequest:statusChange }

view_request:
    path: /requests
    defaults: { _controller: AdminBundle:EmployeeRequest:request }

add_event_accepted_request:
    path: /addevent/acceptrequest
    defaults: { _controller: AdminBundle:EmployeeRequest:addRequestCalendar }

notif_page:
    path: /notif
    defaults: { _controller: AdminBundle:EmployeeRequest:notif }

edit_request:
    path: /request/edit
    defaults: { _controller: AdminBundle:EmployeeRequest:editRequest }

delete_request:
    path: /request/delete
    defaults: { _controller: AdminBundle:EmployeeRequest:deleteRequest }


time_in:
    path: /timein
    defaults: { _controller: AdminBundle:Employee:TimeIn }

time_out:
    path: /timeout/
    defaults: { _controller: AdminBundle:Employee:TimeOut }

time_out_w_params:
    path: /timeout/{passw}
    defaults: { _controller: AdminBundle:Employee:TimeOut }

auto_time_out:
    path: /autotimeout
    defaults: { _controller: AdminBundle:Employee:AutoTimeOut }

admin_manage_working_time_new_day:
    path: /admin/timein/{type}
    defaults: { _controller: AdminBundle:Employee:ManageTimeOnNewDay }

time_logs_page:
    path: /timelogs
    defaults: { _controller: AdminBundle:Employee:timeLogs}

export:
    path: /export
    defaults: {_controller: AdminBundle:Employee:export }

emp_page_w_params:
    path: /emp/{id}
    defaults: { _controller: AdminBundle:Employee:employeeProfile }

emp_page:
    path: /emp/
    defaults: { _controller: AdminBundle:Employee:employeeProfile }

profile_page:
    path: /profile/records/
    defaults: { _controller: AdminBundle:Employee:profile }

manage_employee:
    path: /manage
    defaults: { _controller: AdminBundle:Employee:manage }

add_employee:
    path: /addemp
    defaults: { _controller: AdminBundle:Employee:addEmployee }

add_position:
    path: /addpos/
    defaults: { _controller: AdminBundle:Employee:addPosition }

add_position_w_params:
    path: /addpos/{id}
    defaults: { _controller: AdminBundle:Employee:addPosition }

add_department:
    path: /adddept/
    defaults: { _controller: AdminBundle:Employee:addDepartment }

add_department_w_params:
    path: /adddept/{id}
    defaults: { _controller: AdminBundle:Employee:addDepartment }

emp_delete:
    path: /delete/
    defaults: { _controller: AdminBundle:Employee:empDelete }

emp_delete_w_params:
    path: /delete/{id}
    defaults: { _controller: AdminBundle:Employee:empDelete }

update_profile:
    path: /update
    defaults: { _controller: AdminBundle:Employee:profileUpdate }

change_pass:
    path: /changepass
    defaults: {_controller: AdminBundle:Employee:changePassword }

check_timein:
    path: /check_timein
    defaults: {_controller: AdminBundle:Employee:checkTimeIn }
# ------------ EMPLOYEE REPORT ---------------
admin_employee_report:
    path: /employee/report
    defaults: { _controller: AdminBundle:EmployeeReport:generateReport }

admin_employee_list_report:
    path: /emplist/report
    defaults: { _controller:AdminBundle:EmployeeReport:generateEmployeeReport }

admin_employee_leave_absences_report:
    path: /employee/leave-absences/report
    defaults: { _controller:AdminBundle:EmployeeReport:generateLeaveAbsencesReport }

manage_events:
    path: /events
    defaults: { _controller: AdminBundle:EventManager:list }

manage_event_add:
    path: /event/save
    defaults: { _controller: AdminBundle:EventManager:save }

manage_event_tag_change_status:
    path: /event/save/tag/status
    defaults: { _controller: AdminBundle:EventManager:updateTagStatus }

notify_event:
    path: /manageevent/notify
    defaults: { _controller: AdminBundle:EventManager:notify }

manage_event_cancel:
    path: /event/cancel
    defaults: { _controller: AdminBundle:EventManager:cancelEvent }

edit_event:
    path: /manageevent/edit
    defaults: { _controller: AdminBundle:EventManager:edit }

delete_event:
    path: /manageevent/delete
    defaults: { _controller: AdminBundle:EventManager:delete }

send_email:
    path: /sendemail/
    defaults: {_controller: AdminBundle:Admin:sendEmail }
